server:
  port: 8080

logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
        security: debug

spring:
  application:
    name: OAuth2WebClient
  security:
    user:
      name: username
      password: password